services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_DB=subscription_manager
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_SSL=disable
      - EXCHANGE_RATE_API_URL=https://api.exchangerate-api.com/v4/latest/USD
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_DB=subscription_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
