apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: subscription-manager-credentials
  namespace: subscription-manager
spec:
  itemPath: vaults/Kubernetes/items/subscription-manager-credentials