{{- if not .Values.credentials.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "subscription-manager.fullname" . }}-credentials
  labels:
    {{- include "subscription-manager.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.credentials.postgresUser | b64enc | quote }}
  postgres-password: {{ .Values.credentials.postgresPassword | b64enc | quote }}
  postgres-db: {{ .Values.credentials.postgresDb | b64enc | quote }}
{{- end }}
